### ISSUE TITLE
Investigate how to test proof verification code

### ISSUE THREAD

**Issue by maxzaver** [near/rainbow-bridge-rs#11]
Similarly to https://github.com/near/rainbow-bridge-rs/issues/10 we have a code that deconstructs the merkle patricia proof https://github.com/near/rainbow-bridge-rs/blob/master/eth-prover/src/lib.rs#L195-L315 but we have few tests that test it: https://github.com/near/rainbow-bridge-rs/blob/master/mintable-fungible-token/src/lib.rs#L978-L1013 All these tests actually use the same proof. We also have tests that verify several real proofs extracted from the real Ethereum nodes: https://github.com/near/rainbow-bridge-rs/blob/master/ci/test_verify_eth_proofs.sh Unfortunately, there is no guarantee that these tests cover all corner cases. Unfortunately, merkle patricia trie (MPT) and RLP format have lots of rules for corner cases, e.g. when MPT is constructed on very small amount of data, or RLP is computed from empty input, etc. We need to verify that our proof code is correct. To do this we need to find a way to generate proofs that touch various corner cases. This issue is about investigating the ways we can generate such proofs. We should consider re-using some of the code, like this one:
* Common tools used by Ethereum clients: https://github.com/paritytech/parity-common
* MPT implementation for Substrate (we should make sure it matches Ethereum implementation if we decide to use it): https://github.com/paritytech/trie

**Comment by mfornet** [comment]
The investigation part of this task is concluded. The proof are agnostic to the type of data being proved, and the merkle-patricia-tree for each type of data (i.e. transactions/receipts/storage) offer the same api to proof information on them. This means that we can test the verification code, by providing both synthetic data that covers 100% of the code, and real data to check the data submitted from our relayers can also be verified. 

The efforts to make this test was started in #12
